// India Location Database (States, Districts, Talukas, and Villages)

export const ALL_STATES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", 
  "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", 
  "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", 
  "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", 
  "Uttarakhand", "West Bengal", "Andaman and Nicobar Islands", "Chandigarh", 
  "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Jammu and Kashmir", "Ladakh", 
  "Lakshadweep", "Puducherry"
].sort();

export const DISTRICTS_BY_STATE: Record<string, string[]> = {
  "Maharashtra": [
    "Ahmednagar", "Akola", "Amravati", "Beed", "Bhandara", "Buldhana", "Chandrapur",
    "Dhule", "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur",
    "Latur", "Mumbai City", "Mumbai Suburban", "Nagpur", "Nanded", "Nandurbar",
    "Nashik", "Osmanabad (Dharashiv)", "Palghar", "Parbhani", "Pune", "Raigad", "Ratnagiri",
    "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane", "Washim", "Yavatmal",
    "Chhatrapati Sambhajinagar (Aurangabad)"
  ].sort(),
  "Gujarat": ["Ahmedabad", "Amreli", "Anand", "Aravalli", "Banaskantha", "Bharuch", "Bhavnagar", "Botad", "Chhota Udepur", "Dahod", "Dang", "Devbhumi Dwarka", "Gandhinagar", "Gir Somnath", "Jamnagar", "Junagadh", "Kheda", "Kutch", "Mahisagar", "Mehsana", "Morbi", "Narmada", "Navsari", "Panchmahal", "Patan", "Porbandar", "Rajkot", "Sabarkantha", "Surat", "Surendranagar", "Tapi", "Vadodara", "Valsad"],
  "Madhya Pradesh": ["Agar Malwa", "Alirajpur", "Anuppur", "Ashoknagar", "Balaghat", "Barwani", "Betul", "Bhind", "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh", "Datia", "Dewas", "Dhar", "Dindori", "Guna", "Gwalior", "Harda", "Hoshangabad", "Indore", "Jabalpur", "Jhabua", "Katni", "Khandwa", "Khargone", "Mandla", "Mandsaur", "Morena", "Narsinghpur", "Neemuch", "Panna", "Raisen", "Rajgarh", "Ratlam", "Rewa", "Sagar", "Satna", "Sehore", "Seoni", "Shahdol", "Shajapur", "Sheopur", "Shivpuri", "Sidhi", "Singrauli", "Tikamgarh", "Ujjain", "Umaria", "Vidisha"],
  "Karnataka": ["Bagalkot", "Ballari", "Belagavi", "Bengaluru Rural", "Bengaluru Urban", "Bidar", "Chamarajanagar", "Chikkaballapur", "Chikkamagaluru", "Chitradurga", "Dakshina Kannada", "Davanagere", "Dharwad", "Gadag", "Hassan", "Haveri", "Kalaburagi", "Kodagu", "Kolar", "Koppal", "Mandya", "Mysuru", "Raichur", "Ramanagara", "Shivamogga", "Tumakuru", "Udupi", "Uttara Kannada", "Vijayapura", "Yadgir"],
  "Tamil Nadu": ["Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Dindigul", "Erode", "Kallakurichi", "Kancheepuram", "Kanyakumari", "Karur", "Krishnagiri", "Madurai", "Mayiladuthurai", "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai", "Ramanathapuram", "Ranipet", "Salem", "Sivaganga", "Tenkasi", "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli", "Tirupathur", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur", "Vellore", "Viluppuram", "Virudhunagar"],
  "Uttar Pradesh": ["Agra", "Aligarh", "Prayagraj", "Ambedkar Nagar", "Amethi", "Amroha", "Auraiya", "Ayodhya", "Azamgarh", "Baghpat", "Bahraich", "Ballia", "Balrampur", "Banda", "Barabanki", "Bareilly", "Basti", "Bhadohi", "Bijnor", "Budaun", "Bulandshahr", "Chandauli", "Chitrakoot", "Deoria", "Etah", "Etawah", "Farrukhabad", "Fatehpur", "Firozabad", "Gautam Buddha Nagar", "Ghaziabad", "Ghazipur", "Gonda", "Gorakhpur", "Hamirpur", "Hapur", "Hardoi", "Hathras", "Jalaun", "Jaunpur", "Jhansi", "Kannauj", "Kanpur Dehat", "Kanpur Nagar", "Kasganj", "Kaushambi", "Kheri", "Kushinagar", "Lalitpur", "Lucknow", "Maharajganj", "Mahoba", "Mainpuri", "Mathura", "Mau", "Meerut", "Mirzapur", "Moradabad", "Muzaffarnagar", "Pilibhit", "Pratapgarh", "Raebareli", "Rampur", "Saharanpur", "Sambhal", "Sant Kabir Nagar", "Shahjahanpur", "Shamli", "Shravasti", "Siddharthnagar", "Sitapur", "Sonbhadra", "Sultanpur", "Unnao", "Varanasi"],
  "Rajasthan": ["Ajmer", "Alwar", "Banswara", "Baran", "Barmer", "Bharatpur", "Bhilwara", "Bikaner", "Bundi", "Chittorgarh", "Churu", "Dausa", "Dholpur", "Dungarpur", "Hanumangarh", "Jaipur", "Jaisalmer", "Jalore", "Jhalawar", "Jhunjhunu", "Jodhpur", "Karauli", "Kota", "Nagaur", "Pali", "Pratapgarh", "Rajsamand", "Sawai Madhopur", "Sikar", "Sirohi", "Sri Ganganagar", "Tonk", "Udaipur"],
  "Andhra Pradesh": ["Anantapur", "Chittoor", "East Godavari", "Guntur", "Krishna", "Kurnool", "Prakasam", "Srikakulam", "Sri Potti Sriramulu Nellore", "Visakhapatnam", "Vizianagaram", "West Godavari", "YSR Kadapa"],
  "Bihar": ["Araria", "Arwal", "Aurangabad", "Banka", "Begusarai", "Bhagalpur", "Bhojpur", "Buxar", "Darbhanga", "East Champaran", "Gaya", "Gopalganj", "Jamui", "Jehanabad", "Kaimur", "Katihar", "Khagaria", "Kishanganj", "Lakhisarai", "Madhepura", "Madhubani", "Munger", "Muzaffarpur", "Nalanda", "Nawada", "Patna", "Purnia", "Rohtas", "Saharsa", "Samastipur", "Saran", "Sheikhpura", "Sheohar", "Sitamarhi", "Siwan", "Supaul", "Vaishali", "West Champaran"],
  "West Bengal": ["Alipurduar", "Bankura", "Birbhum", "Cooch Behar", "Dakshin Dinajpur", "Darjeeling", "Hooghly", "Howrah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kolkata", "Malda", "Murshidabad", "Nadia", "North 24 Parganas", "Paschim Bardhaman", "Paschim Medinipur", "Purba Bardhaman", "Purba Medinipur", "Purulia", "South 24 Parganas", "Uttar Dinajpur"],
  "Punjab": ["Amritsar", "Barnala", "Bathinda", "Faridkot", "Fatehgarh Sahib", "Fazilka", "Ferozepur", "Gurdaspur", "Hoshiarpur", "Jalandhar", "Kapurthala", "Ludhiana", "Mansa", "Moga", "Muktsar", "Pathankot", "Patiala", "Rupnagar", "Sahibzada Ajit Singh Nagar", "Sangrur", "Shahid Bhagat Singh Nagar", "Sri Muktsar Sahib", "Tarn Taran"],
  "Haryana": ["Ambala", "Bhiwani", "Charkhi Dadri", "Faridabad", "Fatehabad", "Gurugram", "Hisar", "Jhajjar", "Jind", "Kaithal", "Karnal", "Kurukshetra", "Mahendragarh", "Nuh", "Palwal", "Panchkula", "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat", "Yamunanagar"],
  "Kerala": ["Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam", "Kottayam", "Kozhikode", "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvananthapuram", "Thrissur", "Wayanad"],
  "Assam": ["Baksa", "Barpeta", "Biswanath", "Bongaigaon", "Cachar", "Charaideo", "Chirang", "Darrang", "Dhemaji", "Dhubri", "Dibrugarh", "Dima Hasao", "Goalpara", "Golaghat", "Hailakandi", "Hojai", "Jorhat", "Kamrup", "Kamrup Metropolitan", "Karbi Anglong", "Karimganj", "Kokrajhar", "Lakhimpur", "Majuli", "Morigaon", "Nagaon", "Nalbari", "Sivasagar", "Sonitpur", "South Salmara-Mankachar", "Tinsukia", "Udalguri", "West Karbi Anglong"],
  "Chhattisgarh": ["Balod", "Baloda Bazar", "Balrampur", "Bastar", "Bemetara", "Bijapur", "Bilaspur", "Dantewada", "Dhamtari", "Durg", "Gariaband", "Janjgir-Champa", "Jashpur", "Kabirdham", "Kanker", "Kondagaon", "Korba", "Koriya", "Mahasamund", "Mungeli", "Narayanpur", "Raigarh", "Raipur", "Rajnandgaon", "Sukma", "Surajpur", "Surguja"],
  "Jharkhand": ["Bokaro", "Chatra", "Deoghar", "Dhanbad", "Dumka", "East Singhbhum", "Garhwa", "Giridih", "Godda", "Gumla", "Hazaribagh", "Jamtara", "Khunti", "Koderma", "Latehar", "Lohardaga", "Pakur", "Palamu", "Ramgarh", "Ranchi", "Sahibganj", "Seraikela-Kharsawan", "Simdega", "West Singhbhum"],
  "Odisha": ["Angul", "Balangir", "Balasore", "Bargarh", "Bhadrak", "Baudh", "Cuttack", "Deogarh", "Dhenkanal", "Gajapati", "Ganjam", "Jagatsinghpur", "Jajpur", "Jharsuguda", "Kalahandi", "Kandhamal", "Kendrapara", "Kendujhar", "Khordha", "Koraput", "Malkangiri", "Mayurbhanj", "Nabarangpur", "Nayagarh", "Nuapada", "Puri", "Rayagada", "Sambalpur", "Subarnapur", "Sundargarh"],
  "Telangana": ["Adilabad", "Bhadradri Kothagudem", "Hyderabad", "Jagtial", "Jangaon", "Jayashankar Bhupalpally", "Jogulamba Gadwal", "Kamareddy", "Karimnagar", "Khammam", "Kumuram Bheem", "Mahabubabad", "Mahabubnagar", "Mancherial", "Medak", "Medchal", "Mulugu", "Nagarkurnool", "Nalgonda", "Narayanpet", "Nirmal", "Nizamabad", "Peddapalli", "Rajanna Sircilla", "Rangareddy", "Sangareddy", "Siddipet", "Suryapet", "Vikarabad", "Wanaparthy", "Warangal Rural", "Warangal Urban", "Yadadri Bhuvanagiri"],
  "Goa": ["North Goa", "South Goa"],
  "Delhi": ["Central Delhi", "East Delhi", "New Delhi", "North Delhi", "North East Delhi", "North West Delhi", "Shahdara", "South Delhi", "South East Delhi", "South West Delhi", "West Delhi"],
  "Jammu and Kashmir": ["Anantnag", "Bandipora", "Baramulla", "Budgam", "Doda", "Ganderbal", "Jammu", "Kathua", "Kishtwar", "Kulgam", "Kupwara", "Poonch", "Pulwama", "Rajouri", "Ramban", "Reasi", "Samba", "Shopian", "Srinagar", "Udhampur"],
  "Himachal Pradesh": ["Bilaspur", "Chamba", "Hamirpur", "Kangra", "Kinnaur", "Kullu", "Lahaul and Spiti", "Mandi", "Shimla", "Sirmaur", "Solan", "Una"],
  "Uttarakhand": ["Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haridwar", "Nainital", "Pauri Garhwal", "Pithoragarh", "Rudraprayag", "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi"]
};

export const TALUKAS_BY_DISTRICT: Record<string, string[]> = {
  "Sangli": ["Miraj", "Walwa", "Tasgaon", "Khanapur (Vita)", "Atpadi", "Kavathemahankal", "Jat", "Shirala", "Palus", "Kadegaon"].sort(),
  "Pune": ["Pune City", "Haveli", "Khed", "Baramati", "Junnar", "Indapur", "Shirur", "Maval", "Mulshi", "Purandhar", "Bhor", "Daund", "Ambegaon", "Velhe"].sort(),
  "Satara": ["Satara", "Karad", "Wai", "Mahabaleshwar", "Phaltan", "Man", "Khatav", "Koregaon", "Patan", "Jawali", "Khandala"].sort(),
  "Kolhapur": ["Karvir", "Panhala", "Shahuwadi", "Kagal", "Hatkanangle", "Shirol", "Radhanagari", "Gaganbawada", "Bhudargad", "Ajara", "Gadhinglaj", "Chandgad"].sort(),
  "Solapur": ["Solapur North", "Solapur South", "Barshi", "Akkalkot", "Mohol", "Pandharpur", "Sangola", "Madha", "Karmala", "Mangalwedha", "Malshiras"].sort(),
  "Ahmednagar": ["Ahmednagar", "Rahuri", "Shrirampur", "Nevasa", "Shevgaon", "Pathardi", "Jamkhed", "Karjat", "Shrigonda", "Parner", "Akole", "Sangamner", "Kopargaon", "Rahata"].sort(),
  "Nashik": ["Nashik", "Sinnar", "Igatpuri", "Trimbakeshwar", "Niphad", "Yeola", "Chandwad", "Nandgaon", "Kalwan", "Baglan (Satana)", "Surgana", "Peint", "Dindori", "Deola", "Malegaon"].sort(),
  "Nagpur": ["Nagpur Urban", "Nagpur Rural", "Kamptee", "Hingna", "Katol", "Narkhed", "Savner", "Kalmeshwar", "Ramtek", "Parseoni", "Mauda", "Kuhi", "Bhiwapur", "Umred"].sort(),
  "Chhatrapati Sambhajinagar (Aurangabad)": ["Chhatrapati Sambhajinagar", "Paithan", "Vaijapur", "Gangapur", "Kannad", "Khuldabad", "Sillod", "Phulambri", "Soegaon"].sort(),
  "Yavatmal": ["Yavatmal", "Pusad", "Umarkhed", "Digras", "Darwha", "Arni", "Ner", "Kalamb", "Babulgaon", "Ghatanji", "Ralegaon", "Maregaon", "Wani", "Mahagaon", "Kelapur (Pandharkawada)", "Zari Jamni"].sort(),
  "Ratnagiri": ["Ratnagiri", "Sangameshwar", "Lanja", "Rajapur", "Chiplun", "Guhagar", "Khed", "Dapoli", "Mandangad"].sort(),
  "Sindhudurg": ["Sawantwadi", "Kudal", "Vengurla", "Malvan", "Kankavli", "Devgad", "Vaibhavwadi", "Dodamarg"].sort(),
  "Raigad": ["Alibag", "Pen", "Murud", "Panvel", "Uran", "Karjat", "Khalapur", "Mangaon", "Roha", "Tala", "Mahad", "Poladpur", "Shrivardhan", "Mhasala"].sort(),
  "Osmanabad (Dharashiv)": ["Osmanabad", "Tuljapur", "Omerga", "Lohara", "Kalamb", "Bhum", "Paranda", "Washi"].sort(),
  "Parbhani": ["Parbhani", "Gangakhed", "Sonpeth", "Pathri", "Manwath", "Palam", "Purna", "Sailu", "Jintur"].sort(),
  "Jalna": ["Jalna", "Ambad", "Bhokardan", "Badnapur", "Ghansawangi", "Partur", "Mantha", "Jafrabad"].sort(),
  "Hingoli": ["Hingoli", "Kalamnuri", "Basmath", "Aundha Nagnath", "Sengao"].sort(),
  "Gadchiroli": ["Gadchiroli", "Aheri", "Armori", "Chamorshi", "Desaiganj (Vadasa)", "Dhanora", "Etapalli", "Korchi", "Kurkheda", "Mulchera", "Sironcha", "Bhamragad"].sort(),
  "Chandrapur": ["Chandrapur", "Bhadravati", "Warora", "Chimur", "Nagbhir", "Brahmapuri", "Sindewahi", "Mul", "Sawali", "Gondpipri", "Korpana", "Rajura", "Ballarpur", "Jiwati", "Pombhurna"].sort(),
  "Amravati": ["Amravati", "Bhatkuli", "Nandgaon Khandeshwar", "Dharni", "Chikhaldara", "Achalpur", "Chandurbazar", "Morshi", "Warud", "Daryapur", "Anjangaon Surji", "Chandur Railway", "Dhamangaon Railway", "Teosa"].sort(),
  "Buldhana": ["Buldhana", "Chikhli", "Deulgaon Raja", "Jalgaon Jamod", "Khamgaon", "Lonar", "Malkapur", "Mehkar", "Motala", "Nandura", "Sangrampur", "Shegaon", "Sindkhed Raja"].sort(),
  "Akola": ["Akola", "Akot", "Balapur", "Patur", "Barshitakli", "Murtizapur", "Telhara"].sort(),
  "Latur": ["Latur", "Udgir", "Ahmedpur", "Nilanga", "Ausa", "Chakur", "Renapur", "Deoni", "Jalkot", "Shirur Anantpal"].sort(),
  "Jalgaon": ["Jalgaon", "Bhusawal", "Yawal", "Raver", "Muktainagar", "Bodwad", "Dharangaon", "Erandol", "Parola", "Amalner", "Chopda", "Pachora", "Bhadgaon", "Chalisgaon", "Jamner"].sort(),
  "Nanded": ["Nanded", "Ardhapur", "Bhokar", "Biloli", "Degloor", "Dharmabad", "Himayatnagar", "Hadgaon", "Kandhar", "Kinwat", "Loha", "Mahoor", "Mudkhed", "Mukhed", "Naigaon", "Umri"].sort(),
  "Beed": ["Beed", "Georai", "Majalgaon", "Wadwani", "Patoda", "Ashti", "Shirur (Kasar)", "Parli", "Ambajogai", "Kaij", "Dharur"].sort(),
  "Washim": ["Washim", "Malegaon", "Mangrulpir", "Manora", "Shirpur", "Risod", "Karanja"].sort(),
  "Thane": ["Thane", "Kalyan", "Murbad", "Bhiwandi", "Shahapur", "Ulhasnagar", "Ambarnath"].sort()
};

export const VILLAGES_BY_TALUKA: Record<string, string[]> = {
  "Palus": [
    "Amanapur",
    "Andhali",
    "Ankalkhop",
    "Anugdewadi",
    "Bambavade",
    "Bhilwadi",
    "Bramhanal",
    "Burli",
    "Burungwadi",
    "Chopdewadi",
    "Dahyari",
    "Dudhondi",
    "Ghogaon",
    "Hajarwadi",
    "Khandobachiwadi",
    "Khatav",
    "Kundal",
    "Malewadi",
    "Morale",
    "Nagrale",
    "Nagthane",
    "Palus",
    "Pundi Tarf Walava",
    "Pundiwadi",
    "Radewadi",
    "Ramanandnagar",
    "Sandgewadi",
    "Sawantpur",
    "Share Dudhondi",
    "Sukhwadi",
    "Suryagaon",
    "Tavdarwadi",
    "Tupari",
    "Vithalwadi",
    "Wasgade"
  ],
  "Tasgaon": [
    "Alate",
    "Anjani",
    "Arwade",
    "Balgavade",
    "Bastawade",
    "Bendri",
    "Bhairvawadi",
    "Biranwadi",
    "Borgaon",
    "Chikhal Gothan",
    "Chinchani",
    "Dahiwadi",
    "Dhavali",
    "Dhondewadi",
    "Dhulgaon",
    "Dongarsoni",
    "Dorli",
    "Gaurgaon",
    "Gavhan",
    "Gotewadi",
    "Hatnoli",
    "Hatnoor",
    "Jarandi",
    "Julewadi",
    "Kacharewadi",
    "Kaulage",
    "Kavathe Ekand",
    "Khalsa Dhamani",
    "Khujagaon",
    "Kindarwadi",
    "Kumathe",
    "Limb",
    "Lode",
    "Lokarewadi",
    "Manerajuri",
    "Manjarde",
    "Matkunki",
    "Morale Ped",
    "Nagaon Kavathe",
    "Nagaon Nimani",
    "Nagewadi",
    "Narsewadi",
    "Nehru Nagar",
    "Nimani",
    "Nimblak",
    "Padali",
    "Panmalewadi",
    "Ped",
    "Punadi",
    "Rajapur",
    "Savalaj",
    "Savarde",
    "Shirgaon Kavathe",
    "Siddhewadi",
    "Sirgaon Visapur",
    "Tasgaon",
    "Turchi",
    "Upalavi",
    "Vajrachaunde",
    "Vanjarwadi",
    "Vijay Nagar",
    "Visapur",
    "Wadgaon",
    "Waghapur",
    "Waifale",
    "Wasumbe",
    "Yamgarwadi",
    "Yelavi",
    "Yogewadi"
  ],
  "Miraj": [
    "Ankali",
    "Arag",
    "Bamani",
    "Bamnoli",
    "Bedag",
    "Belanki",
    "Bhose",
    "Bisur",
    "Bolwad",
    "Chabukswarwadi",
    "Dhavali",
    "Dongarwadi",
    "Dudhgaon",
    "Erandoli",
    "Gundewadi",
    "Haripur",
    "Inam Dhamani",
    "Janaraowadi",
    "Kadamwadi",
    "Kakadwadi",
    "Kalambi",
    "Kanadwadi",
    "Karnal",
    "Karoli",
    "Kasabe Digraj",
    "Kavaji Khotwadi",
    "Kavalapur",
    "Kavathe Piran",
    "Khanderajuri",
    "Kharkatwadi",
    "Khatav",
    "Kupwad",
    "Laxmiwadi",
    "Lingnur",
    "Madhavnagar",
    "Malewadi",
    "Malgaon",
    "Malwadi",
    "Manmodi",
    "Mhaisal",
    "Miraj",
    "Mouje Digraj",
    "Nandra",
    "Narwad",
    "Nilaji",
    "Padmale",
    "Patgaon",
    "Payappachiwadi",
    "Rasulwadi",
    "Salgare",
    "Sambarwadi",
    "Samdoli",
    "Sangli",
    "Santoshwadi",
    "Savali",
    "Savalwadi",
    "Sheri Kavathe",
    "Shindewadi",
    "Shipur",
    "Siddhewadi",
    "Soni",
    "Takali",
    "Tanang",
    "Tung",
    "Vaddi",
    "Vijay Nagar",
    "Vyankuchiwadi",
    "Wajegaon"
  ],
  "Walwa": [
    "Ahirwadi",
    "Aitavade Bk",
    "Aitavade Kh",
    "Ashta",
    "Bagani",
    "Bahadurwadi",
    "Bahe",
    "Banewadi",
    "Bavchi",
    "Beradmachi",
    "Bhadkimbe",
    "Bharatwadi",
    "Bhatwadi",
    "Bhavaninagar",
    "Bichud",
    "Borgaon",
    "Chikurde",
    "Devarde",
    "Dhagewadi",
    "Dhavali",
    "Dhotrewadi",
    "Dongarwadi",
    "Dudhari",
    "Farnewadi",
    "Gatadwadi",
    "Gaundwadi",
    "Ghabakwadi",
    "Gotkhindi",
    "Hubalwadi",
    "Islampur",
    "Itakare",
    "Jakraiwadi",
    "Jambhulwadi",
    "June Khed",
    "Kakachiwadi",
    "Kalamwadi",
    "Kameri",
    "Kanegaon",
    "Kapuskhed",
    "Karandwadi",
    "Karanjvade",
    "Karve",
    "Kasegaon",
    "Kedarwadi",
    "Kharatwadi",
    "Kille Machhindra Gad",
    "Kole",
    "Konoli",
    "Koregaon",
    "Krishnanagar",
    "Kundalwadi",
    "Kurlap",
    "Ladegaon",
    "Lavanmachi",
    "Mahadevwadi",
    "Malewadi",
    "Manikwadi",
    "Maralnathpur",
    "Mardawadi",
    "Masuchiwadi",
    "Mirajwadi",
    "Nagaon",
    "Narsihapur",
    "Nave Khed",
    "Naykalwadi",
    "Nerle",
    "Ozarde",
    "Padavalwadi",
    "Peth",
    "Phalkewadi & Chandachiwadi",
    "Pharnewadi",
    "Pokharni",
    "Rethare Dharan",
    "Rethare Harnaksha",
    "Rozawadi",
    "Sakharale",
    "Satapewadi",
    "Shekharwadi",
    "Shene",
    "Shigaon",
    "Shirate",
    "Shirgaon",
    "Shivpuri",
    "Surul",
    "Takari",
    "Tambave",
    "Tandulwadi",
    "Thanapude",
    "Tujarpur",
    "Vashi",
    "Vitthalwadi",
    "Waghwadi",
    "Walwa",
    "Wategaon",
    "Yede Machchhindra",
    "Yede Nipani",
    "Yelur",
    "Yewalewadi"
  ],
  "Kavathe Mahankal": [
    "Agalgaon",
    "Alkud",
    "Alkud [s]",
    "Arewadi",
    "Banewadi",
    "Bassappawadi",
    "Borgaon",
    "Chorochi",
    "Chudekhindi",
    "Deshing",
    "Dhalewadi",
    "Dhalgaon",
    "Dholewadi",
    "Dhulgaon",
    "Dudhebhavi",
    "Garjewadi",
    "Ghatnandre",
    "Ghorpadi",
    "Haroli",
    "Hingangaon",
    "Irali",
    "Jadhavwadi",
    "Jakhapur",
    "Jambhulwadi",
    "Jaygavhan",
    "Kadamwadi",
    "Karalhetti",
    "Karoli",
    "Kavathe Mahankal",
    "Kerewadi",
    "Kharshing",
    "Kognoli",
    "Kokale",
    "Kuchi",
    "Kuktoli",
    "Kundlapur",
    "Landgewadi",
    "Langarpeth",
    "Lonarwadi",
    "Malangaon",
    "Mhaisal",
    "Moghamwadi",
    "Morgaon",
    "Nagaj",
    "Nangole",
    "Nimaj",
    "Pimpalwadi",
    "Rampurwadi",
    "Ranjani",
    "Raywadi",
    "Sarati",
    "Shelkewadi",
    "Shindewadi",
    "Shirdhon",
    "Thabadewadi",
    "Tisangi",
    "Vithurayachi Wadi",
    "Wagholi",
    "Zurewadi"
  ],
  "Khanapur (Vita)": [
    "Ainwadi",
    "Alsund",
    "Balvadi",
    "Balvadi Bhalvani",
    "Bamani",
    "Banurgad",
    "Benapur",
    "Bhadakewadi",
    "Bhagyanagar",
    "Bhalwani",
    "Bhambarde",
    "Bhendvade",
    "Bhikawadi Bk.",
    "Bhood",
    "Chikhalhol",
    "Chinchani",
    "Devikhindi",
    "Devnagar",
    "Dhawaleshwar",
    "Dhondewadi",
    "Dhondgewadi",
    "Gardi",
    "Ghadgewadi",
    "Ghanwad",
    "Ghoti Bk",
    "Ghoti Kh",
    "Gorewadi",
    "Himgangade",
    "Hivare",
    "Jadhavnagar",
    "Jadhavwadi",
    "Jakhinwadi",
    "Jondhalkhindi",
    "Kalambi",
    "Kamlapur",
    "Karanje",
    "Karve",
    "Khambale Bhalvani",
    "Khanapur",
    "Kurli",
    "Kusbavade",
    "Lengre",
    "Madhalmuthi",
    "Mahuli",
    "Mangrul",
    "Menganwadi",
    "Mohi",
    "Nagewadi",
    "Palashi",
    "Panchlingnagar",
    "Pare",
    "Posewadi",
    "Ramnagar",
    "Renavi",
    "Rewangaon",
    "Salshinge",
    "Sangole",
    "Shendgewadi",
    "Sultangade",
    "Tadachiwadi",
    "Tandalgaon",
    "Vejegaon",
    "Vita",
    "Walkhad",
    "Waluj",
    "Wasumbe",
    "Wazar"
  ],
  "Atpadi": [
    "Ambewadi",
    "Atpadi",
    "Autewadi",
    "Awalai",
    "Balewadi",
    "Banpuri",
    "Bhingewadi",
    "Bombewadi",
    "Chinchale",
    "Deshamukhwadi",
    "Dhavadwadi",
    "Dighanchi",
    "Galavewadi",
    "Ghanand",
    "Gharniki",
    "Gomewadi",
    "Gulewadi",
    "Hivtad",
    "Jambhulni",
    "Kalewadi",
    "Kamth",
    "Kankatrewadi",
    "Kargani",
    "Kautholi",
    "Khanjodwadi",
    "Kharsundi",
    "Kurundwadi",
    "Lengrewadi",
    "Lingivare",
    "Madgule",
    "Malewadi",
    "Manewadi",
    "Maptemala",
    "Masalwadi",
    "Mitki",
    "Mudhewadi",
    "Nelkaranji",
    "Nimbawade",
    "Padalkarwadi",
    "Palaskhel",
    "Pandharewadi",
    "Parekarwadi",
    "Patrewadi",
    "Pimpari Bk.",
    "Pimpari Kh",
    "Pisewadi",
    "Pujarwadi",
    "Rajewadi",
    "Sherewadi",
    "Shetphale",
    "Tadvale",
    "Talewadi",
    "Umbargaon",
    "Vibhutwadi",
    "Vithalapur",
    "Wakasewadi",
    "Walwan",
    "Yamaji Patalachi Wadi",
    "Zare"
  ],
  "Jath": [],
  "Kadegaon": [
    "Ambak",
    "Ambegaon",
    "Amrapur",
    "Apsinge",
    "Asad",
    "Belavade",
    "Bhikawadi Kh",
    "Bombalewadi",
    "Chikhali",
    "Chinchani Wangi",
    "Devrashtre",
    "Dhanewadi",
    "Hanmant Vadiye",
    "Hingangaon Bk",
    "Hingangaon Kh",
    "Kadegaon",
    "Kadepur",
    "Kanharwadi",
    "Karandewadi",
    "Khambale Aundh",
    "Kherade Vita",
    "Kheradewangi",
    "Kotawade",
    "Kotij",
    "Kumbhargaon",
    "Mohityache Vadgaon",
    "Nerli",
    "Nevari",
    "Nimsod",
    "Padali",
    "Ramapur",
    "Raygaon",
    "Renusewadi",
    "Saholi",
    "Saspade",
    "Shalgaon",
    "Shelakbav",
    "Shirasgaon",
    "Shirgaon",
    "Shivajinagar",
    "Shivani",
    "Sonkire",
    "Sonsal",
    "Tadasar",
    "Tondoli",
    "Tupewadi",
    "Tupewadi (1)",
    "Upale Mayani",
    "Upalewangi",
    "Vadiye-Raybag",
    "Vihapur",
    "Wang Rethare",
    "Wangi",
    "Yede",
    "Yetgaon",
    "Yevlewadi"
  ]
};

export function normalizeNameForMatch(name: string): string {
  if (!name) return '';
  const englishMatch = name.match(/^([^\(]+)/);
  const base = englishMatch ? englishMatch[1] : name;
  return base.replace(/[^a-zA-Z0-9]/g, '').trim().toUpperCase().replace(/W/g, 'V');
}

export const normalizeTalukaName = (name: string, district?: string): string => {
  if (!name) return "";
  const norm = normalizeNameForMatch(name);
  
  // Mapping of common variations to canonical names
  const mapping: Record<string, string> = {
    "TASGAON": "Tasgaon",
    "TASGANV": "Tasgaon",
    "MIRAJ": "Miraj",
    "MIRA": "Miraj",
    "SANGOLA": "Sangola",
    "SANGLI": "Sangli",
    "KHANAPUR": "Khanapur",
    "VITA": "Khanapur",
    "ATPADI": "Atpadi",
    "JATH": "Jath",
    "KAVATHEMAHANKAL": "Kavathe Mahankal",
    "KAVATHEMAHANKAAL": "Kavathe Mahankal",
    "PALUS": "Palus",
    "KADAL": "Kadal",
    "WALWA": "Walwa",
    "ISLAMPUR": "Walwa",
    "SHIRALA": "Shirala"
  };

  return mapping[norm] || name.trim();
};

export const getTalukasForDistrict = (district: string): string[] => {
  if (!district) return [];
  const normDist = district.toLowerCase().trim();
  const matchedKey = Object.keys(TALUKAS_BY_DISTRICT).find(
    k => k.toLowerCase().trim() === normDist
  );
  return matchedKey ? TALUKAS_BY_DISTRICT[matchedKey] : [];
};

export const getVillagesForTaluka = (taluka: string): string[] => {
  if (!taluka) return [];
  const normTaluka = normalizeNameForMatch(taluka);
  const matchedKey = Object.keys(VILLAGES_BY_TALUKA).find(
    k => normalizeNameForMatch(k) === normTaluka
  );
  return matchedKey ? VILLAGES_BY_TALUKA[matchedKey] : [];
};

export const isVillageOfficialForTaluka = (villageName: string, talukaName: string): boolean => {
  if (!villageName || !talukaName) return false;
  const normVillage = normalizeNameForMatch(villageName);
  const masterVillages = getVillagesForTaluka(talukaName);
  return masterVillages.some(v => normalizeNameForMatch(v) === normVillage);
};

export const MAHARASHTRA_DISTRICTS = DISTRICTS_BY_STATE["Maharashtra"];
